import type { CSSProperties } from "react";
import type { StageDef, Unit, UnitDef } from "../game/types";
import { ELEMENT_CLASS } from "../game/constants";
import { BattleUnit } from "./BattleUnit";
type BattleState="playing"|"victory"|"defeat"|"stageSelect";
type DeathEffect={id:number;x:number;team:"hero"|"enemy";life:number};
type DamagePopup={id:number;x:number;value:number;critical?:boolean};
type Props={stage:StageDef;stageIndex:number;unlockedStage:number;battleState:BattleState;castleHp:number;enemyCastleHp:number;battleGold:number;battleGoldMax:number;economyLevel:number;economyMaxLevel:number;goldPerSecond:number;economyUpgradeCost:number;waveIndex:number;gameSpeed:number;autoCom:boolean;heroes:Unit[];enemies:Unit[];deathEffects:DeathEffect[];damagePopups:DamagePopup[];castleHit:"our"|"enemy"|null;bossPhaseTwo:boolean;bossDisplayIcon:string;bossDisplayName:string;bossHpPercent:number;bossUnit?:Unit;bossCharge:number;bossPhase:number;waveProgress:number;notice:string;waveThreat:string;visibleDeck:UnitDef[];deployCooldowns:Record<string,number>;deckCount:number;deckSlotCount:number;kingdomLevel:number;ownedHeroCount:number;heroTotal:number;getUnitLevel:(id:string)=>number;onSpeed:()=>void;onAuto:()=>void;onUpgradeEconomy:()=>void;onDeploy:(hero:UnitDef)=>void;onRetry:()=>void;onStageSelect:()=>void;onNext:()=>void};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
export function BattleScreen(p:Props){const bossWave=p.stage.waveMeta[p.waveIndex]?.boss;return <main className="game-shell">
<header className="topbar"><div><div className="game-title">BREAK THE WALLS</div><div className="sub-title">퓨어 월드 · STAGE {p.stage.id} · {p.stage.name}</div></div><div className="top-stats"><div className="stat-pill">🏰 우리 성 <b>{Math.ceil(p.castleHp)}</b></div><div className="stat-pill gold">🪙 Battle Gold <b>{Math.floor(p.battleGold).toLocaleString()} / {p.battleGoldMax.toLocaleString()}</b></div><div className="stat-pill">💰 지갑 <b>Lv.{p.economyLevel}/{p.economyMaxLevel}</b></div><div className="stat-pill">🗺️ STAGE <b>{p.stage.id}</b> · 🌊 <b>{Math.min(p.waveIndex+1,p.stage.waves.length)}/{p.stage.waves.length}</b></div><button className="stat-pill speed-control" onClick={p.onSpeed}>⚡ {p.gameSpeed}X</button><button className={`stat-pill auto-com-control ${p.autoCom?"active":""}`} onClick={p.onAuto}>🤖 AUTO {p.autoCom?"ON":"OFF"}</button></div></header>
<section className="battle-card"><div className="battle-sky"><div className="pixel-sky-grid"/><div className="cloud c1"/><div className="cloud c2"/><div className="mountains"/><div className="battle-horizon"/><div className="battle-title-plate">⚔️ FRONTLINE</div>
<div className={`castle our-castle ${p.castleHit==="our"?"castle-hit":""}`}><div className="tower">🏰</div><div className="castle-label">우리 성</div><div className="castle-hp"><span style={{width:`${clamp(p.castleHp/10,0,100)}%`}}/></div></div>
<div className={`castle enemy-castle ${p.castleHit==="enemy"?"castle-hit":""}`}><div className="tower">🏯</div><div className="castle-label">적 성</div><div className="castle-hp enemy"><span style={{width:`${clamp(p.enemyCastleHp/18,0,100)}%`}}/></div></div>
<div className="lane"><div className="lane-ground"/><div className="lane-grid"/><div className="lane-center-line"/><div className="castle-zone our-zone"/><div className="castle-zone enemy-zone"/>{p.heroes.map(u=><BattleUnit key={u.uid} unit={u}/>)}{p.enemies.map(u=><BattleUnit key={u.uid} unit={u}/>)}{p.deathEffects.map(e=><div key={e.id} style={{position:"absolute",zIndex:17,left:String(e.x)+"%",top:e.team==="hero"?"42%":"48%",transform:"translate(-50%,-50%)",fontSize:25,pointerEvents:"none",opacity:Math.min(1,e.life*3)}}>{e.team==="hero"?"💥":"💢"}</div>)}{p.damagePopups.map(d=><div key={d.id} className={`damage-popup ${d.critical?"critical":""}`} style={{left:`${d.x}%`}}>-{d.value}</div>)}</div>
{bossWave&&<div className={`boss-bar ${p.bossPhaseTwo?"enraged":""}`}><div className="boss-title">{p.bossDisplayIcon} BOSS · {p.bossDisplayName} {p.bossPhaseTwo?"· ENRAGED":""}</div><div className="boss-hp"><span style={{width:`${p.bossHpPercent}%`}}/></div><div className="boss-hp-text">{p.bossUnit?`${Math.ceil(p.bossUnit.currentHp)} / ${p.bossUnit.hp}`:"등장 준비 중"}</div>{p.bossUnit&&<div className="boss-mechanic-status">{p.stage.id===40?`전하 ${Math.min(10,Math.floor(p.bossCharge/4))}/10`:p.stage.id===50&&p.stage.bossMechanic?.phaseElements?`현재 페이즈 · ${p.stage.bossMechanic.phaseElements[Math.max(0,p.bossPhase)]??p.stage.bossMechanic.phaseElements[0]}`:p.stage.mechanic}</div>}</div>}
<div className="wave-banner"><div className="wave-title">STAGE {p.stage.id} · WAVE {p.waveIndex+1}/{p.stage.waves.length} · {p.stage.waveMeta[p.waveIndex]?.name}</div><div className="wave-progress"><span style={{width:`${clamp(p.waveProgress,0,100)}%`}}/></div><div className="wave-notice">{p.notice}</div>{p.waveThreat&&<div className="wave-threat">{p.waveThreat}</div>}</div></div>
<div className="economy-panel"><div className="economy-info"><b>💰 전투 지갑 Lv.{p.economyLevel}/{p.economyMaxLevel}</b><span>초당 +{p.goldPerSecond} 🪙 · 최대 {p.battleGoldMax.toLocaleString()}</span></div><button className="economy-upgrade" disabled={p.economyLevel>=p.economyMaxLevel||p.battleGold<p.economyUpgradeCost} onClick={p.onUpgradeEconomy}>{p.economyLevel>=p.economyMaxLevel?"지갑 MAX":`지갑 강화 · 🪙 ${p.economyUpgradeCost}`}</button></div>
<div className="deck-panel"><div className="battle-deck-header"><b>⚔️ 출전 영웅</b><span>카드를 눌러 전장에 배치 · {p.deckCount}/{p.deckSlotCount}</span></div><div className="deck-slots">{p.visibleDeck.map(hero=>{const cd=p.deployCooldowns[hero.id]??0,lacks=p.battleGold<hero.cost,cooling=cd>0,disabled=lacks||cooling;return <div key={hero.id} className={`hero-card-wrap ${disabled?"disabled":""}`}><button className={`hero-card ${disabled?"disabled":""}`} onClick={()=>p.onDeploy(hero)}><div className={`hero-sprite ${ELEMENT_CLASS[hero.element]}`}>{hero.sprite}<span className="spark"/></div><div className="hero-name">{hero.name} <small>Lv.{p.getUnitLevel(hero.id)}</small></div><div className="hero-meta"><span>{hero.role}</span><b>🪙 {hero.cost}</b></div><div className="hero-combat-type"><span>{hero.rangeType==="melee"?"⚔️ 근접":"🏹 원거리"}</span><span>{hero.attackType==="splash"?"💥 광역":"🎯 단일"}</span></div><div className="hero-ability">{hero.ability==="guard"&&"🛡️ 피해 감소 22%"}{hero.ability==="regen"&&"✚ 초당 HP 회복"}{hero.ability==="crit"&&"⚡ 28% 치명타"}{hero.ability==="execute"&&"☠️ 저체력 적 추가 피해"}{!hero.ability&&hero.attackType==="splash"&&"💥 광역 공격"}{!hero.ability&&hero.effect==="burn"&&hero.attackType!=="splash"&&"🔥 화상"}</div><div className="cooldown">{cd>0?`⏱ ${cd.toFixed(1)}s`:lacks?`🪙 ${Math.ceil(hero.cost-p.battleGold)} 부족`:"⚔️ 출격 가능"}</div>{cooling&&<div className="cooldown-mask" style={{"--cooldown-ratio":`${Math.min(100,(cd/hero.cooldown)*100)}%`} as CSSProperties}/>}</button></div>})}</div></div>
<div className="deck-indicator">영웅 편성 {p.deckCount}/{p.deckSlotCount} · 영지 Lv.{p.kingdomLevel} · 보유 {p.ownedHeroCount}/{p.heroTotal}</div></section>
<section className="battle-info"><div><b>자동전투</b><span>영웅은 자동으로 이동·공격·스킬 발동</span></div><div><b>속성</b><span>⚪ 무속성 · 🔥 불 · 🌑 어둠</span></div><div><b>현재 적</b><span>{p.enemies.filter(e=>e.alive).length}기</span></div></section>
{p.battleState!=="playing"&&<div className="result-overlay"><div className={`result-box ${p.battleState}`}><div className="result-kicker">{p.battleState==="victory"?"STAGE CLEAR":"STAGE FAILED"}</div><h1>{p.battleState==="victory"?"적 성을 돌파했다!":"성이 함락됐다..."}</h1><p>{p.battleState==="victory"?`STAGE ${p.stage.id} 클리어! 최초 클리어 시 ${p.stage.clearReward} 골드 + ${p.stage.firstClearGems} 보석 · 다음 전장/채집 지역이 해금됩니다.`:"덱과 배치 타이밍을 바꿔 다시 도전하자."}</p><div className="result-actions"><button onClick={p.onRetry}>다시 전투</button><button onClick={p.onStageSelect}>스테이지 선택</button>{p.battleState==="victory"&&p.stageIndex+1<p.unlockedStage&&<button onClick={p.onNext}>다음 스테이지 ▶</button>}</div></div></div>}
</main>}