import type { UnitDef } from "../game/types";
import type { SummonStorageItem } from "../game/systems/summon";
type Phase="idle"|"throw"|"impact"|"crack"|"reveal";
type Props={heroes:UnitDef[];phase:Phase;sequence:SummonStorageItem[];revealIndex:number;summaryOpen:boolean;results:SummonStorageItem[];gems:number;soulShards:number;transcendShards:number;legendPity:number;mythPity:number;message:string;storageCount:number;fusionCount:number;fusionTotal:number;ownedCount:number;onSkip:()=>void;onNext:()=>void;onCloseSummary:()=>void;onSummon:(count:1|11)=>void;onStorage:()=>void;onFusion:()=>void};
export function SummonPanel(p:Props){const item=p.sequence[p.revealIndex],hero=item?p.heroes.find(h=>h.id===item.heroId):undefined,high=item?["전설","신화","초월"].includes(item.grade):false,omen=item?.grade??"일반";return <div className="summon-panel hub-summon">
 <div className="deck-builder-title">🎲 성벽 소환</div>
 {p.phase!=="idle"&&<div className={`summon-cinematic phase-${p.phase} grade-scene-${omen} ${high?"high-grade summon-fakeout":""}`}><button className="summon-skip" onClick={p.onSkip}>SKIP</button><div className="summon-scene"><div className="summon-moon">✦</div><div className="summon-die">🎲</div><div className="summon-wall"><div className="wall-top">▥▥▥</div><div className="wall-body">▦▦▦<i>⚡</i>▦▦▦</div></div><div className="summon-impact-ring"/><div className="summon-omen">{p.phase==="crack"&&item&&<><span>◆</span><b>{["일반","희귀"].includes(item.grade)?"...":item.grade==="영웅"?"강한 기척":"성벽이 버티지 못한다"}</b></>}</div>{high&&p.phase==="crack"&&<div className="second-die">🎲</div>}{p.phase==="reveal"&&hero&&item&&<div className={`hero-reveal grade-${item.grade}`} onClick={p.onNext}><div className="reveal-rays"/><small>{p.revealIndex+1} / {p.sequence.length}</small><div className="reveal-grade">{item.grade}</div><div className="reveal-sprite">{hero.sprite}</div><h2>{hero.name}</h2><p>{hero.role}</p><b>{p.revealIndex<p.sequence.length-1?"클릭하여 다음 영웅 ▶":"클릭하여 결과 확인"}</b></div>}</div>{p.phase!=="reveal"&&<div className="summon-cinematic-text">{p.phase==="throw"?"운명의 주사위를 던진다":p.phase==="impact"?"성벽과 운명이 충돌한다":"균열 너머에서 기척이 느껴진다..."}</div>}</div>}
 {p.summaryOpen&&p.results.length>0&&<div className="summon-summary-overlay"><div className="summon-summary-box"><div className="summon-summary-title"><div><small>SUMMON RESULT</small><h2>{p.results.length===11?"10+1 소환 결과":"소환 결과"}</h2></div><button onClick={p.onCloseSummary}>✕</button></div><div className="summon-summary-grid">{p.results.map(r=>{const h=p.heroes.find(x=>x.id===r.heroId);return h?<div key={r.uid} className={`summary-card grade-${r.grade}`}><span>{h.sprite}</span><b>{h.name}</b><small>{r.grade}</small></div>:null})}</div><button className="summary-confirm" onClick={p.onCloseSummary}>보관소 확인</button></div></div>}
 <p>소환 결과는 바로 영웅이 되지 않고 저장소로 이동합니다. 사용할 영웅만 영입하거나 영혼으로 변환하세요.</p><div className="summon-gem-balance">💎 <b>{p.gems.toLocaleString()}</b> · 🧩 영혼 파편 <b>{p.soulShards.toLocaleString()}</b> · ✦ 초월 조각 <b>{p.transcendShards}</b></div>
 <div className="summon-actions"><button className="summon-btn" disabled={p.gems<100} onClick={()=>p.onSummon(1)}>🎲 1회 소환 · 100 💎</button><button className="summon-btn multi" disabled={p.gems<1000} onClick={()=>p.onSummon(11)}>🎲 10+1 소환 · 1000 💎<small>11명 소환 · 마지막 1명 영웅 이상 보장</small></button></div>
 <div className="summon-rates">일반 65% · 희귀 25% · 영웅 7% · 전설 2.5% · 신화 0.45% · 초월 0.05%</div><div className="summon-pity"><span>전설 이상 천장 <b>{p.legendPity}/100</b></span><span>신화 이상 천장 <b>{p.mythPity}/500</b></span></div>{p.message&&<div className="summon-result">{p.message}</div>}
 <button className="open-storage-btn" onClick={p.onStorage}>📦 저장소 열기 <b>{p.storageCount}</b></button><button className="open-storage-btn fusion-open" onClick={p.onFusion}>⚗️ 영웅 합성소 <b>{p.fusionCount}/{p.fusionTotal}</b></button><div className="owned-count">실사용 보유 영웅 {p.ownedCount}/{p.heroes.length}</div>
 </div>}